# NumPy

### (Otherwise Python is just too slow and cumbersome.)

---
## Import the numpy module

In [2]:
# To use the numpy module we need to import it.
# If you didn't already have the module,
# you would first need to get it (e.g. via Anaconda Navigator).
import numpy

In [3]:
a1 = numpy.array([1,2,3,4,5,6,7,8])
a1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [3]:
# import ___ as ALIAS for shorthand notation
import numpy as np

a2 = np.array([[1,2],[3,4],[5,6]])
a2

array([[1, 2],
       [3, 4],
       [5, 6]])

## <font color=red>Exercises</font>

1. Print out the type of object that a1 is.

---
## Add/Manage modules

* via Anaconda Navigator UI
* via command line, e.g.:
    * `conda install numpy` installs the numpy module
    * `conda list numpy` lists the numpy module if it is installed
    * `conda update numpy` updates the numpy module to the latest version

---
## Python Environments

It is ususally recommended that you use distinct enviroments (collections of modules) for each of your projects.

!!! *We are **NOT** going to talk about this right now, but I recommend that you look into this topic on your own after you have a working understanding of Python modules (we'll cover these in a later lecture).*

---
## ndarray (n-dimensional array)

#### shape = (rows, columns, depth, higher dimensions...)

![numpy shape](images/numpy_shape.png)

In [ ]:
a1 = numpy.array([1,2,3,4,5,6,7,8])
a2 = np.array([[1,2],[3,4],[5,6]])

a1.shape, a2.shape

In [ ]:
a3 = a1.reshape((2,2,2))
a3

## <font color=red>Exercises</font>

1. Print out the number of rows in **a2**? Hint: Use **a2**'s shape attribute.

2. Use the 1D array **a1** below to create a matrix with rows [1,2,3] and [4,5,6].

In [4]:
a1 = np.arange(1,7)  #start, stop, step
a1

array([1, 2, 3, 4, 5, 6])

---
## Follow the link below for a graphical tour of ndarrays

[Let's check out Jay Alammar's graphical depictions of ndarrays!](http://jalammar.github.io/visual-numpy/)

---
## Now we'll just recap a few things

---
## Indexing

#### [rows, columns, depth, ...]

![NumPy indexing](images/numpy_indexing.png)

## <font color=red>Exercises</font>

In [ ]:
# the above pictured matrix
# !!! By the end of this lecture you should understand this next line !!!
a = np.arange(36).reshape((6,6)) + np.arange(6).reshape((6,1)) * 4
a

1. Pair off with one of your neighbors. One of you explain the red selection to the other, then vice versa for the last lime green selection.

2. Change the value of the element in the 3rd row and 2nd column to 100.

3. Set every other row in the last column to zero.

---
## Initializing

In [5]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
shape = (2,3)
np.ones(shape)

In [ ]:
mat = np.random.random((2,3,2))
mat

---
## Broadcasting

![NumPy broadcasting](images/numpy_broadcasting.png)

In [ ]:
a = np.array([0,10,20,30]).reshape((-1,1))  # -1 => as many elements as needed
b = np.array([0,1,2]).reshape((1,-1))  # -1 => as many elements as needed
a

In [ ]:
b

In [ ]:
a+b

In [ ]:
a*b

In [ ]:
c = a*b*10
c

---
## Reductions

In [ ]:
c.min(), c.max(), c.mean(), c.std()

In [ ]:
c.max(axis=0)  # max along rows

In [ ]:
c.max(axis=1)  # max along columns

---
## ndarrays and slices into ndarrays are mutable

In [5]:
a = np.zeros((2,3))
b = a  # a and b now refer to the same data
b[1,1] = 1
a

array([[0., 0., 0.],
       [0., 1., 0.]])

In [ ]:
b = a[0,:]  # b refers to a part of the same data that a does (the first row)
b

In [ ]:
b[2] = 2
a

In [ ]:
b[:] = [1,2,3]  # changes the data values that b refers to
a

In [ ]:
c = b  # b and c both refer to same data (the first row of data that a refers to)
c[0] = 100
a

In [ ]:
b = [4,5,6]  # !!! this sets b to new data and removes any association with a or c
a

In [ ]:
b

---
## Load some EEG data

!!! Note, how I extracted the eeg data below is not important, it just happens to be how it is arranged in the data file.

**What's important is that you can understand the arrangement of the eeg ndarray and manipulate it.**

In [29]:
from scipy.io import loadmat  # I'm using loadmat from the io submodule of the scipy module
data = loadmat('eeg.mat')  # load data saved in MATLAB format

# Grab relevant data into an ndarray with dimensions (channel, time, trial).
# Each channel is an electrode and each trial is a separate EEG recording from that electrode.
# So eeg is an ndarray where each row is a time series recording from a particular electrode channel
# and depth reflects repeated recordings from the same channel.
eeg = data["EEG"][0,0]["data"]  # [channel, time, trial]

eeg.shape

(64, 640, 99)

## <font color=red>Exercises</font>

1. Draw a 3D schematic of the **eeg** ndarray indicating what each dimension represents.

2. Print the number of electrodes by getting it from **eeg.shape**. Use a formatted print statement to make it read nice.

3. Create a new variable **trace** that refers to the 3rd channel's 1st trial EEG record.

4. Create an array containing the time-averaged EEG value ($\mu$V) for each trial in channel 10. **!!! Note that the shape of a subarray is NOT the shape of the original array!**

5. Create a new EEG array with each channel's average EEG across trials. What should the shape of this new array be?