# Numba

#### Let's accelerate functions with Python loops and NumPy computations!

[A quick intro!](https://numba.pydata.org/numba-doc/dev/user/5minguide.html)

In [1]:
import numpy as np
import numba

In [9]:
x = np.arange(100).reshape(10, 10)

@numba.jit # or @numba.njit takes away all python

def go_fast(mat): # Function is compiled to machine code when called the first time
    trace = 0
    rows = mat.shape[0]
    for i in range(rows):          # Numba likes loops
        trace += np.tanh(mat[i,i]) # Numba likes NumPy functions
    return mat + trace             # Numba likes NumPy broadcasting

print(go_fast(x)) # numba makes it more efficient when using loops

[[  9.  10.  11.  12.  13.  14.  15.  16.  17.  18.]
 [ 19.  20.  21.  22.  23.  24.  25.  26.  27.  28.]
 [ 29.  30.  31.  32.  33.  34.  35.  36.  37.  38.]
 [ 39.  40.  41.  42.  43.  44.  45.  46.  47.  48.]
 [ 49.  50.  51.  52.  53.  54.  55.  56.  57.  58.]
 [ 59.  60.  61.  62.  63.  64.  65.  66.  67.  68.]
 [ 69.  70.  71.  72.  73.  74.  75.  76.  77.  78.]
 [ 79.  80.  81.  82.  83.  84.  85.  86.  87.  88.]
 [ 89.  90.  91.  92.  93.  94.  95.  96.  97.  98.]
 [ 99. 100. 101. 102. 103. 104. 105. 106. 107. 108.]]


In [6]:
%%timeit
# 1. Make sure there are no lines such as "@numba.jit" just before the go_fast function definition.
# 2. Rerun the cell defining go_fast.
# 3. Run this cell.
go_fast(x)

723 ns ± 2.93 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


## numba.jit

just-in-time compiler (JIT)

In [ ]:
%%timeit
# 1. Add the line "@numba.jit" just before the go_fast function definition.
# 2. Rerun the cell defining go_fast.
# 3. Run this cell.
go_fast(x)

## numba.njit

no leftover Python

In [ ]:
%%timeit
# 1. Add the line "@numba.njit" just before the go_fast function definition.
# 2. Rerun the cell defining go_fast.
# 3. Run this cell.
go_fast(x)

## A Gotcha!

!!! WARNING !!! Note that the full speedup from jit is only seen the *2nd time* the function is used! This is because there is overhead to perform the compilation the first time around.

In [10]:
%%timeit
# 1. Comment out the `print(go_fast(x))` line following the function definition.
# 2. Rerun the cell defining go_fast.
# 3. Run this cell.
go_fast(x)

754 ns ± 3.61 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
